/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * CountryInfo Dto
 *
 * @param commonName CommonName
 * @param officialName OfficialName
 * @param countryCode CountryCode
 * @param region Region
 * @param borders Country Borders
 */
@Serializable

data class CountryInfoDto (

    /* CommonName */
    @SerialName(value = "commonName") val commonName: kotlin.String? = null,

    /* OfficialName */
    @SerialName(value = "officialName") val officialName: kotlin.String? = null,

    /* CountryCode */
    @SerialName(value = "countryCode") val countryCode: kotlin.String? = null,

    /* Region */
    @SerialName(value = "region") val region: kotlin.String? = null,

    /* Country Borders */
    @SerialName(value = "borders") val borders: kotlin.collections.List<CountryInfoDto>? = null

)

