/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Long Weekend
 *
 * @param startDate StartDate
 * @param endDate EndDate
 * @param dayCount DayCount
 * @param needBridgeDay NeedBridgeDay
 */
@Serializable

data class LongWeekendV3Dto (

    /* StartDate */
    @SerialName(value = "startDate") val startDate: kotlin.String? = null,

    /* EndDate */
    @SerialName(value = "endDate") val endDate: kotlin.String? = null,

    /* DayCount */
    @SerialName(value = "dayCount") val dayCount: kotlin.Int? = null,

    /* NeedBridgeDay */
    @SerialName(value = "needBridgeDay") val needBridgeDay: kotlin.Boolean? = null

)

