/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PublicHolidayType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Public Holiday
 *
 * @param date The date
 * @param localName Local name
 * @param name English name
 * @param countryCode ISO 3166-1 alpha-2
 * @param fixed Is this public holiday every year on the same date
 * @param global Is this public holiday in every county (federal state)
 * @param counties ISO-3166-2 - Federal states
 * @param launchYear The launch year of the public holiday
 * @param types A list of types the public holiday it is valid
 */
@Serializable

data class PublicHolidayV3Dto (

    /* The date */
    @SerialName(value = "date") val date: kotlin.String? = null,

    /* Local name */
    @SerialName(value = "localName") val localName: kotlin.String? = null,

    /* English name */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* ISO 3166-1 alpha-2 */
    @SerialName(value = "countryCode") val countryCode: kotlin.String? = null,

    /* Is this public holiday every year on the same date */
    @SerialName(value = "fixed") val fixed: kotlin.Boolean? = null,

    /* Is this public holiday in every county (federal state) */
    @SerialName(value = "global") val global: kotlin.Boolean? = null,

    /* ISO-3166-2 - Federal states */
    @SerialName(value = "counties") val counties: kotlin.collections.List<kotlin.String>? = null,

    /* The launch year of the public holiday */
    @SerialName(value = "launchYear") val launchYear: kotlin.Int? = null,

    /* A list of types the public holiday it is valid */
    @SerialName(value = "types") val types: kotlin.collections.List<@Contextual PublicHolidayType>? = null

)

