/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brettm.holiday.holidayApi.apis

import org.openapitools.client.models.CountryInfoDto
import org.openapitools.client.models.CountryV3Dto

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import kotlinx.serialization.*
import kotlinx.serialization.encoding.*

open class CountryApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    constructor(
        baseUrl: String
    ): super(baseUrl = baseUrl, httpClientEngine = null, httpClientConfig = null, jsonBlock = ApiClient.JSON_DEFAULT)

    /**
     * Get all available countries
     * 
     * @return kotlin.collections.List<CountryV3Dto>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun availableCountries(): HttpResponse<kotlin.collections.List<CountryV3Dto>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v3/AvailableCountries",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<CountryAvailableCountriesResponse>().map { value }
    }

    @Serializable
    private class CountryAvailableCountriesResponse(val value: List<CountryV3Dto>) {
        companion object : KSerializer<CountryAvailableCountriesResponse> {
            private val serializer: KSerializer<List<CountryV3Dto>> = serializer<List<CountryV3Dto>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: CountryAvailableCountriesResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = CountryAvailableCountriesResponse(
                serializer.deserialize(decoder))
        }
    }

    /**
     * Get country info for the given country
     * 
     * @param countryCode 
     * @return CountryInfoDto
     */
    @Throws(Exception::class)
    open suspend fun countryInfo(countryCode: kotlin.String): HttpResponse<CountryInfoDto> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v3/CountryInfo/{countryCode}".replace("{" + "countryCode" + "}", "$countryCode"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }
}
